version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_scrapy
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/app  # Scrapyプロジェクトのルート（scrapy.cfgがあるディレクトリ）
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]